/**
 * Build the delirium policy microsite.
 *
 *   node src/build.mjs [path/to/policy.md]
 *
 * Reads the policy markdown (single source of truth), renders every page into
 * docs/, compiles the stylesheet, copies nhsuk-frontend JavaScript, writes the
 * search index and checks internal links.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import * as sass from 'sass'

import { parsePolicy } from './lib/policy.mjs'
import { createMarkdown } from './lib/markdown.mjs'
import { site } from './lib/site.mjs'
import { checkLinks } from './lib/check-links.mjs'
import { buildHub } from './pages/hub.mjs'
import { buildPathway } from './pages/pathway.mjs'
import { buildTasks } from './pages/tasks.mjs'
import { buildPolicyPages } from './pages/policy.mjs'
import { buildAbout, buildHelp, buildSearch } from './pages/misc.mjs'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SOURCE = path.resolve(ROOT, process.argv[2] || 'Delirium_Policy_DRAFT_v0.1.md')
const OUT = path.join(ROOT, 'docs')
const MARKER = path.join(OUT, '.generated-by-build')
const NHSUK = path.join(ROOT, 'node_modules', 'nhsuk-frontend', 'dist', 'nhsuk')

function prepareOutputDir() {
  if (fs.existsSync(OUT)) {
    if (!fs.existsSync(MARKER) && fs.readdirSync(OUT).length) {
      throw new Error(`${OUT} exists and was not created by this build. Move it aside or delete it first.`)
    }
    fs.rmSync(OUT, { recursive: true, force: true })
  }
  fs.mkdirSync(OUT, { recursive: true })
  fs.writeFileSync(MARKER, 'This directory is generated by `npm run build`. Do not edit by hand.\n')
  fs.writeFileSync(path.join(OUT, '.nojekyll'), '')
}

function write(relPath, content) {
  const p = path.join(OUT, relPath)
  fs.mkdirSync(path.dirname(p), { recursive: true })
  fs.writeFileSync(p, content)
}

function main() {
  if (!fs.existsSync(SOURCE)) throw new Error(`Policy source not found: ${SOURCE}`)
  const markdown = fs.readFileSync(SOURCE, 'utf8')
  const policy = parsePolicy(markdown)
  const version = (policy.metaValue('Status').match(/v\d+\.\d+/) || ['v?'])[0]

  const collected = []
  const collect = (item) => collected.push(item)
  const md = createMarkdown({ site, policy })
  const ctx = { site, policy, md, version, collect, sourceName: path.basename(SOURCE) }

  prepareOutputDir()

  // Pages (about is built last so it can list every collected marker)
  const pages = [
    buildHub(ctx),
    buildPathway(ctx),
    ...buildTasks(ctx),
    ...buildPolicyPages(ctx),
    buildHelp(ctx),
    buildSearch(ctx)
  ]
  pages.push(buildAbout(ctx, collected))

  for (const p of pages) write(p.page.url, p.html)

  // Search index
  const index = pages.flatMap((p) => p.searchEntries || []).map((e) => ({
    title: e.title,
    section: e.section,
    url: e.url,
    text: e.text
  }))
  write(site.urls.searchIndex, JSON.stringify(index))

  // Assets
  write('javascripts/nhsuk-frontend.min.js', fs.readFileSync(path.join(NHSUK, 'nhsuk-frontend.min.js')))
  write('javascripts/search.js', fs.readFileSync(path.join(ROOT, 'src', 'js', 'search.js')))
  write('javascripts/tree.js', fs.readFileSync(path.join(ROOT, 'src', 'js', 'tree.js')))
  write('javascripts/app.js', fs.readFileSync(path.join(ROOT, 'src', 'js', 'app.js')))
  const imagesDir = path.join(ROOT, 'src', 'assets', 'images')
  for (const f of fs.readdirSync(imagesDir)) {
    if (f.startsWith('.')) continue
    write(path.posix.join('assets/images', f), fs.readFileSync(path.join(imagesDir, f)))
  }

  // Stylesheet
  const css = sass.compile(path.join(ROOT, 'src', 'styles', 'app.scss'), {
    loadPaths: [path.join(ROOT, 'node_modules')],
    style: 'compressed',
    quietDeps: true
  })
  write('stylesheets/app.css', css.css)

  // Link check
  const { files, errors } = checkLinks(OUT)
  console.log(`Built ${files} pages from ${path.basename(SOURCE)} (policy ${version}) into docs/`)
  console.log(`Search index: ${index.length} entries. Items to confirm collected: ${collected.length}.`)
  if (errors.length) {
    console.error(`\n${errors.length} broken internal link(s):`)
    for (const e of errors) console.error(`  - ${e}`)
    process.exitCode = 1
  } else {
    console.log('Internal links: all resolve.')
  }
}

main()
